USE KurtisDB;
GO

-- SEED DATA

INSERT INTO dbo.Brands (Label) VALUES
('Kurtis Originals'),
('Vastra Vogue'),
('Ethnic Essence'),
('Royal Threads'),
('Urban Desi');
GO

INSERT INTO dbo.Categories (Label) VALUES
('Cotton Kurtis'),
('Silk Kurtis'),
('Anarkali'),
('Straight Fit'),
('Festive Wear'),
('Casual Wear');
GO

INSERT INTO dbo.Collections (Name, Description) VALUES
('Summer Bloom', 'Bright and breezy kurtis for summer comfort.'),
('Royal Heritage', 'Intricate designs inspired by Indian royal attire.'),
('Modern Minimal', 'Simple and elegant daily wear kurtis.'),
('Festive Spark', 'Vibrant kurtis perfect for celebration season.');
GO

INSERT INTO dbo.Users (Username, PasswordHash, Role)
VALUES 
('admin', 'HASHED_ADMIN_PASSWORD', 'Admin'),
('customer1', 'HASHED_CUSTOMER_PASSWORD', 'User');
GO


INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Kurtis Model #1', N'Handcrafted Kurtis by FabWeave — item 1.', 1233, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 1.7, 5, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Suits Model #2', N'Handcrafted Suits by UrbanEthnic — item 2.', 1466, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 2.4, 10, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Lehengas Model #3', N'Handcrafted Lehengas by FestiveCraft — item 3.', 1699, 1563, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 3.1, 15, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Jackets Model #4', N'Handcrafted Jackets by RoyalLoom — item 4.', 1932, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 3.8, 20, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Accessories Model #5', N'Handcrafted Accessories by FabWeave — item 5.', 2165, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 4.5, 25, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Kurtis Model #6', N'Handcrafted Kurtis by UrbanEthnic — item 6.', 2398, 2134, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 1.2, 30, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Suits Model #7', N'Handcrafted Suits by FestiveCraft — item 7.', 2631, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 1.9, 35, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Lehengas Model #8', N'Handcrafted Lehengas by RoyalLoom — item 8.', 2864, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 2.6, 40, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Jackets Model #9', N'Handcrafted Jackets by FabWeave — item 9.', 3097, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 3.3, 45, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Accessories Model #10', N'Handcrafted Accessories by UrbanEthnic — item 10.', 3330, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 4.0, 50, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Kurtis Model #11', N'Handcrafted Kurtis by FestiveCraft — item 11.', 3563, 3349, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 4.7, 55, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Suits Model #12', N'Handcrafted Suits by RoyalLoom — item 12.', 3796, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 1.4, 60, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Lehengas Model #13', N'Handcrafted Lehengas by FabWeave — item 13.', 4029, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 2.1, 65, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Jackets Model #14', N'Handcrafted Jackets by UrbanEthnic — item 14.', 4262, 3878, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 2.8, 70, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Accessories Model #15', N'Handcrafted Accessories by FestiveCraft — item 15.', 4495, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 3.5, 75, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Kurtis Model #16', N'Handcrafted Kurtis by RoyalLoom — item 16.', 4728, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 4.2, 80, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Suits Model #17', N'Handcrafted Suits by FabWeave — item 17.', 4961, 4365, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 4.9, 85, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Lehengas Model #18', N'Handcrafted Lehengas by UrbanEthnic — item 18.', 5194, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 1.6, 90, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Jackets Model #19', N'Handcrafted Jackets by FestiveCraft — item 19.', 5427, 3581, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 2.3, 95, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Accessories Model #20', N'Handcrafted Accessories by RoyalLoom — item 20.', 5660, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 3.0, 0, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Kurtis Model #21', N'Handcrafted Kurtis by FabWeave — item 21.', 5893, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 3.7, 5, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Suits Model #22', N'Handcrafted Suits by UrbanEthnic — item 22.', 1126, 1047, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 4.4, 10, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Lehengas Model #23', N'Handcrafted Lehengas by FestiveCraft — item 23.', 1359, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 1.1, 15, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Jackets Model #24', N'Handcrafted Jackets by RoyalLoom — item 24.', 1592, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 1.8, 20, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Accessories Model #25', N'Handcrafted Accessories by FabWeave — item 25.', 1825, 1642, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 2.5, 25, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Kurtis Model #26', N'Handcrafted Kurtis by UrbanEthnic — item 26.', 2058, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 3.2, 30, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Suits Model #27', N'Handcrafted Suits by FestiveCraft — item 27.', 2291, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 3.9, 35, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Lehengas Model #28', N'Handcrafted Lehengas by RoyalLoom — item 28.', 2524, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 4.6, 40, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Jackets Model #29', N'Handcrafted Jackets by FabWeave — item 29.', 2757, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 1.3, 45, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Accessories Model #30', N'Handcrafted Accessories by UrbanEthnic — item 30.', 2990, 2840, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 2.0, 50, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Kurtis Model #31', N'Handcrafted Kurtis by FestiveCraft — item 31.', 3223, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 2.7, 55, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Suits Model #32', N'Handcrafted Suits by RoyalLoom — item 32.', 3456, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 3.4, 60, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Lehengas Model #33', N'Handcrafted Lehengas by FabWeave — item 33.', 3689, 3393, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 4.1, 65, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Jackets Model #34', N'Handcrafted Jackets by UrbanEthnic — item 34.', 3922, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 4.8, 70, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Accessories Model #35', N'Handcrafted Accessories by FestiveCraft — item 35.', 4155, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 1.5, 75, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Kurtis Model #36', N'Handcrafted Kurtis by RoyalLoom — item 36.', 4388, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 2.2, 80, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Suits Model #37', N'Handcrafted Suits by FabWeave — item 37.', 4621, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 2.9, 85, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Lehengas Model #38', N'Handcrafted Lehengas by UrbanEthnic — item 38.', 4854, 3252, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 3.6, 90, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Jackets Model #39', N'Handcrafted Jackets by FestiveCraft — item 39.', 5087, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 4.3, 95, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Accessories Model #40', N'Handcrafted Accessories by RoyalLoom — item 40.', 5320, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 1.0, 0, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Kurtis Model #41', N'Handcrafted Kurtis by FabWeave — item 41.', 5553, 5219, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 1.7, 5, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Suits Model #42', N'Handcrafted Suits by UrbanEthnic — item 42.', 5786, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 2.4, 10, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Lehengas Model #43', N'Handcrafted Lehengas by FestiveCraft — item 43.', 1019, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 3.1, 15, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Jackets Model #44', N'Handcrafted Jackets by RoyalLoom — item 44.', 1252, 1139, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 3.8, 20, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Accessories Model #45', N'Handcrafted Accessories by FabWeave — item 45.', 1485, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 4.5, 25, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Kurtis Model #46', N'Handcrafted Kurtis by UrbanEthnic — item 46.', 1718, 1185, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 1.2, 30, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Suits Model #47', N'Handcrafted Suits by FestiveCraft — item 47.', 1951, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 1.9, 35, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Lehengas Model #48', N'Handcrafted Lehengas by RoyalLoom — item 48.', 2184, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 2.6, 40, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Jackets Model #49', N'Handcrafted Jackets by FabWeave — item 49.', 2417, 1595, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 3.3, 45, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Accessories Model #50', N'Handcrafted Accessories by UrbanEthnic — item 50.', 2650, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 4.0, 50, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Kurtis Model #51', N'Handcrafted Kurtis by FestiveCraft — item 51.', 2883, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 4.7, 55, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Suits Model #52', N'Handcrafted Suits by RoyalLoom — item 52.', 3116, 2897, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 1.4, 60, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Lehengas Model #53', N'Handcrafted Lehengas by FabWeave — item 53.', 3349, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 2.1, 65, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Jackets Model #54', N'Handcrafted Jackets by UrbanEthnic — item 54.', 3582, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 2.8, 70, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Accessories Model #55', N'Handcrafted Accessories by FestiveCraft — item 55.', 3815, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 3.5, 75, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Kurtis Model #56', N'Handcrafted Kurtis by RoyalLoom — item 56.', 4048, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 4.2, 80, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Suits Model #57', N'Handcrafted Suits by FabWeave — item 57.', 4281, 2911, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 4.9, 85, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Lehengas Model #58', N'Handcrafted Lehengas by UrbanEthnic — item 58.', 4514, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 1.6, 90, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Jackets Model #59', N'Handcrafted Jackets by FestiveCraft — item 59.', 4747, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 2.3, 95, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Accessories Model #60', N'Handcrafted Accessories by RoyalLoom — item 60.', 4980, 4731, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 3.0, 0, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Kurtis Model #61', N'Handcrafted Kurtis by FabWeave — item 61.', 5213, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 3.7, 5, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Suits Model #62', N'Handcrafted Suits by UrbanEthnic — item 62.', 5446, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 4.4, 10, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Lehengas Model #63', N'Handcrafted Lehengas by FestiveCraft — item 63.', 5679, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 1.1, 15, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Jackets Model #64', N'Handcrafted Jackets by RoyalLoom — item 64.', 5912, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 1.8, 20, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Accessories Model #65', N'Handcrafted Accessories by FabWeave — item 65.', 1145, 801, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 2.5, 25, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Kurtis Model #66', N'Handcrafted Kurtis by UrbanEthnic — item 66.', 1378, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 3.2, 30, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Suits Model #67', N'Handcrafted Suits by FestiveCraft — item 67.', 1611, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 3.9, 35, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Lehengas Model #68', N'Handcrafted Lehengas by RoyalLoom — item 68.', 1844, 1235, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 4.6, 40, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Jackets Model #69', N'Handcrafted Jackets by FabWeave — item 69.', 2077, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 1.3, 45, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Accessories Model #70', N'Handcrafted Accessories by UrbanEthnic — item 70.', 2310, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 2.0, 50, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Kurtis Model #71', N'Handcrafted Kurtis by FestiveCraft — item 71.', 2543, 2390, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 2.7, 55, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Suits Model #72', N'Handcrafted Suits by RoyalLoom — item 72.', 2776, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 3.4, 60, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Lehengas Model #73', N'Handcrafted Lehengas by FabWeave — item 73.', 3009, 2166, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 4.1, 65, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Jackets Model #74', N'Handcrafted Jackets by UrbanEthnic — item 74.', 3242, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 4.8, 70, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Accessories Model #75', N'Handcrafted Accessories by FestiveCraft — item 75.', 3475, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 1.5, 75, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Kurtis Model #76', N'Handcrafted Kurtis by RoyalLoom — item 76.', 3708, 2558, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 2.2, 80, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Suits Model #77', N'Handcrafted Suits by FabWeave — item 77.', 3941, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 2.9, 85, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Lehengas Model #78', N'Handcrafted Lehengas by UrbanEthnic — item 78.', 4174, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 3.6, 90, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Jackets Model #79', N'Handcrafted Jackets by FestiveCraft — item 79.', 4407, 2908, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 4.3, 95, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Accessories Model #80', N'Handcrafted Accessories by RoyalLoom — item 80.', 4640, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 1.0, 0, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Kurtis Model #81', N'Handcrafted Kurtis by FabWeave — item 81.', 4873, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 1.7, 5, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Suits Model #82', N'Handcrafted Suits by UrbanEthnic — item 82.', 5106, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 2.4, 10, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Lehengas Model #83', N'Handcrafted Lehengas by FestiveCraft — item 83.', 5339, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 3.1, 15, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Jackets Model #84', N'Handcrafted Jackets by RoyalLoom — item 84.', 5572, 3956, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 3.8, 20, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Accessories Model #85', N'Handcrafted Accessories by FabWeave — item 85.', 5805, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 4.5, 25, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Kurtis Model #86', N'Handcrafted Kurtis by UrbanEthnic — item 86.', 1038, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 1.2, 30, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Suits Model #87', N'Handcrafted Suits by FestiveCraft — item 87.', 1271, 864, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 1.9, 35, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Lehengas Model #88', N'Handcrafted Lehengas by RoyalLoom — item 88.', 1504, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 2.6, 40, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Jackets Model #89', N'Handcrafted Jackets by FabWeave — item 89.', 1737, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 3.3, 45, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Accessories Model #90', N'Handcrafted Accessories by UrbanEthnic — item 90.', 1970, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 4.0, 50, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Kurtis Model #91', N'Handcrafted Kurtis by FestiveCraft — item 91.', 2203, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'male', N'["XS","S","M","L","XL"]', 4.7, 55, 0, 0, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Suits Model #92', N'Handcrafted Suits by RoyalLoom — item 92.', 2436, 1778, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'female', N'["XS","S","M","L"]', 1.4, 60, 0, 1, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Lehengas Model #93', N'Handcrafted Lehengas by FabWeave — item 93.', 2669, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'male', N'["XS","S","M"]', 2.1, 65, 0, 0, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Jackets Model #94', N'Handcrafted Jackets by UrbanEthnic — item 94.', 2902, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'female', N'["XS","S"]', 2.8, 70, 0, 1, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Accessories Model #95', N'Handcrafted Accessories by FestiveCraft — item 95.', 3135, 2194, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'male', N'["XS"]', 3.5, 75, 0, 0, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Kurtis Model #96', N'Handcrafted Kurtis by RoyalLoom — item 96.', 3368, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Kurtis')), 'female', N'["XS","S","M","L","XL"]', 4.2, 80, 0, 1, N'["https://images.unsplash.com/photo-1595429035839-c99c298ffdde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FabWeave Suits Model #97', N'Handcrafted Suits by FabWeave — item 97.', 3601, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FabWeave')), ((SELECT Id FROM dbo.Categories WHERE Label='Suits')), 'male', N'["XS","S","M","L"]', 4.9, 85, 1, 0, N'["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'UrbanEthnic Lehengas Model #98', N'Handcrafted Lehengas by UrbanEthnic — item 98.', 3834, 2568, ((SELECT Id FROM dbo.Brands WHERE Label='UrbanEthnic')), ((SELECT Id FROM dbo.Categories WHERE Label='Lehengas')), 'female', N'["XS","S","M"]', 1.6, 90, 0, 1, N'["https://images.unsplash.com/photo-1611042553480-a35c5ca1c835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'FestiveCraft Jackets Model #99', N'Handcrafted Jackets by FestiveCraft — item 99.', 4067, NULL, ((SELECT Id FROM dbo.Brands WHERE Label='FestiveCraft')), ((SELECT Id FROM dbo.Categories WHERE Label='Jackets')), 'male', N'["XS","S"]', 2.3, 95, 0, 0, N'["https://images.unsplash.com/photo-1592124549776-a7f0cc973b24?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO dbo.Products ([Name], Description, Price, DiscountedPrice, BrandId, CategoryId, AverageRating, RatingCount, ImageUrlsJson, CreatedAt, UpdatedAt) VALUES (N'RoyalLoom Accessories Model #100', N'Handcrafted Accessories by RoyalLoom — item 100.', 4300, 3225, ((SELECT Id FROM dbo.Brands WHERE Label='RoyalLoom')), ((SELECT Id FROM dbo.Categories WHERE Label='Accessories')), 'female', N'["XS"]', 3.0, 0, 1, 1, N'["https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=500&w=500"]', SYSUTCDATETIME(), SYSUTCDATETIME());
GO

INSERT INTO dbo.Inventories (ProductId, Size, Quantity)
VALUES
(1, 'S', 25),
(1, 'M', 40),
(1, 'L', 30),
(2, 'S', 20),
(2, 'M', 50),
(3, 'L', 45),
(4, 'S', 15),
(4, 'M', 25),
(5, 'L', 20),
(5, 'XL', 10);
GO

INSERT INTO dbo.ProductCollections (ProductId, CollectionId)
VALUES
(1, 1),
(2, 2),
(3, 2),
(4, 3),
(5, 4);
GO
